[selinux] More precise warnings when installing policy fails

diff --git a/omnibus/package-scripts/agent/posttrans b/omnibus/package-scripts/agent/posttrans
--- a/omnibus/package-scripts/agent/posttrans
+++ b/omnibus/package-scripts/agent/posttrans
@@ -57,28 +57,37 @@ fi
 
 # SELinux policy not shipped on SUSE for now
 if [ "$DISTRIBUTION_FAMILY" != "SUSE" ]; then
-    # Setup SELinux policy and label if SELinux detected on the host
-    if command -v semodule >/dev/null 2>&1 && [ -f "$INSTALL_DIR/embedded/bin/system-probe" ]; then
-        echo "Loading SELinux policy module for datadog-agent."
-        semodule -v -i $CONFIG_DIR/selinux/system_probe_policy.pp >/dev/null 2>&1
-        if [ "$?" != "0" ]; then
-            echo "The SELinux policy module for datadog-agent is not compatible with this host."
-            echo "Please install or update the selinux-policy-targeted package and then reinstall the datadog-agent package to configure SELinux for the Datadog Agent."
-            echo "Skipping SELinux configuration."
-        else
-            echo "Labeling SELinux type for the system-probe binary."
-            if command -v semanage >/dev/null 2>&1 && command -v restorecon >/dev/null 2>&1;then
-                semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe && restorecon -v $INSTALL_DIR/embedded/bin/system-probe
-                if [ "$?" != "0" ]; then
-                    echo "Could not relabel the system-probe binary with type system_probe_t."
-                fi
-            else
-                echo "Could not set up SELinux labels for datadog-agent: semanage and/or restorecon commands not found."
-                echo "Please make sure they are installed (via the policycoreutils, policycoreutils-python and/or policycoreutils-python-utils packages), and then run:"
-                echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe"
-                echo "    restorecon -v $INSTALL_DIR/embedded/bin/system-probe"
+    # Setup SELinux policy and label if SELinux detected on the host and in enforcing mode
+    if [ -f "$INSTALL_DIR/embedded/bin/system-probe" ] && command -v getenforce >/dev/null 2>&1 && getenforce | grep -i "enforcing" >/dev/null 2>&1; then
+        echo "SELinux detected in enforcing mode."
+        if command -v semodule >/dev/null 2>&1 && command -v semanage >/dev/null 2>&1 && command -v restorecon >/dev/null 2>&1 && [ -f "$INSTALL_DIR/embedded/bin/system-probe" ]; then
+            echo "Loading SELinux policy module for datadog-agent and labeling SELinux type for the system-probe binary."
+            semodule -v -i $CONFIG_DIR/selinux/system_probe_policy.pp >/dev/null 2>&1 && semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe && restorecon -v $INSTALL_DIR/embedded/bin/system-probe
+            if [ "$?" != "0" ]; then
+                echo "Couldn’t load system-probe policy."
+                echo "To be able to run system-probe on your host, please install or upgrade the selinux-policy-targeted and"
+                echo "policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
+                SHOW_SELINUX_COMMANDS=true
             fi
+        else
+            echo "Couldn’t load system-probe policy (missing selinux utilities)."
+            echo "To be able to run system-probe on your host, please install or upgrade the selinux-policy-targeted and"
+            echo "policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
+            SHOW_SELINUX_COMMANDS=true
         fi
+    elif [ -f "$INSTALL_DIR/embedded/bin/system-probe" ] && command -v getenforce >/dev/null 2>&1; then
+        # SELinux is present, but not enforcing
+        echo "SELinux detected but not in enforcing mode."
+        echo "To be able to run system-probe on your host with SELinux in enforcing mode, please install or upgrade the"
+        echo "selinux-policy-targeted and policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
+        SHOW_SELINUX_COMMANDS=true
+    fi
+
+    if [ -n "$SHOW_SELINUX_COMMANDS" ]; then
+        echo "Then run the following commands:"
+        echo "  semodule -i $CONFIG_DIR/selinux/system_probe_policy.pp"
+        echo "  semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe"
+        echo "  restorecon -v $INSTALL_DIR/embedded/bin/system-probe"
     fi
 fi
 
